version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5050:5050"  
    networks:
      - envoy-net

  mongo:
    image: 'mongo:7.0.5'
    ports:
      - 27018:27017

  mongo-express:
    image: 'mongo-express:1.0.2'
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: username
      ME_CONFIG_BASICAUTH_PASSWORD: password

  timescale:
    image: timescale/timescaledb-ha:pg16
    ports:
      - "5432:5432" 
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - envoy-net

  docs:
    image: wongnai/grpcui
    ports:
      - "8081:8080"  
    environment:
      - GRPCUI_SERVER=server:5050
    networks:
      - envoy-net

  envoy:
    image: envoyproxy/envoy:v1.27-latest
    ports:
      - "8080:8080"
    expose:
      - "8080"
    volumes:
      - ./gateway/envoy.yaml:/etc/envoy/envoy.yaml
    networks:
      - envoy-net

networks:
  envoy-net: